export const GET_COURSES = "GET_COURSES"
export const GET_SINGLE_COURSES = "GET_SINGLE_COURSES"
export const GET_ABOUT = "GET_ABOUT"
export const GET_COURSES_TEST = "GET_COURSES_TEST"
export const GET_COURSES_TEST_DETAILS = "GET_COURSES_TEST_DETAILS"
export const GET_ADMIN = "GET_ADMIN"
export const GET_USER = "GET_USER"

